# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/sdx/sdx/discussions
    about: |
      Use sdx's GitHub Discussions to ask "How do I do X with sdx?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/sdx/sdx
    about: |
      The sdx tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of sdx.
  - name: ğŸ“  sdx Code of Conduct
    url: https://github.com/sdx/sdx/coc/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on sdx's GitHub.
